name: Convert RemixIcon Glyph to Expo

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  convert-glyph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download RemixIcon Glyph
        run: |
          curl -LJO https://raw.githubusercontent.com/Remix-Design/RemixIcon/master/fonts/remixicon.glyph.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run conversion script
        run: python convert_glyph.py

      - name: Replace existing remixicon.expo.json
        run: mv remixicon.expo.json ./remixicon.expo.json

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add remixicon.expo.json
          git commit -m "Update Expo-compatible glyph data"
          git push
